version: '3'

services:
  python-3.12:  # nosemgrep
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: $USER-python-3.12-fastagencyapi
    volumes:
      - ../../:/workspaces/fastagencyapi:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://admin:password@${USER}-postgres-py312-fastagencyapi:5432/fastagency
      - PY_DATABASE_URL=postgresql://admin:password@${USER}-postgres-py312-fastagencyapi:5432/pyfastagency
      - NATS_URL=nats://${USER}-nats-py312-fastagencyapi:4222
    env_file:
      - ../devcontainer.env
    networks:
      - fastagencyapi-network
  nats-fastagency:  # nosemgrep
    image: nats:latest
    container_name: $USER-nats-py312-fastagencyapi
    # ports:
      # - "${PORT_PREFIX}4222:4222"
      # - "${PORT_PREFIX}9222:9222"
    volumes:
      - ../nats_server.conf:/etc/nats/server.conf
    command: [ "--config", "/etc/nats/server.conf" ]
    env_file:
      - ../devcontainer.env
    networks:
      - fastagencyapi-network
  postgres-fastagency:  # nosemgrep
    image: postgres:latest
    container_name: $USER-postgres-py312-fastagencyapi
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password  # pragma: allowlist secret
      POSTGRES_DB: fastagency
    # ports:
    #   - "${PORT_PREFIX}5432:5432"
    networks:
      - fastagencyapi-network

networks:
  fastagencyapi-network:
    name: "${USER}-fastagencyapi-network"
